<div class="mermaid">
sequenceDiagram
  User->>Cloud Controller:cf bind-service
  Cloud Controller->>On Demand Broker:PUT binding
  On Demand Broker->>Service Adapter:create-binding
  Service Adapter->>On Demand Broker:binding credentials
  On Demand Broker->>Cloud Controller:binding credentials
  Cloud Controller->>User:OK
</div>
