<div class="mermaid">
sequenceDiagram
  User->> Cloud Foundry: cf create-service
  Cloud Foundry->> ODB: POST instance (create)
  ODB->>Service Adapter: generate-manifest
  Service Adapter->>ODB: manifest
  ODB->>BOSH: deploy
  BOSH->>ODB: accepted
  ODB->>Cloud Foundry: accepted
  Cloud Foundry->>User: OK
  loop until bosh task is complete
    Cloud Foundry->>ODB: GET last operation
    ODB->>BOSH: GET deploy task
    BOSH->>ODB: task in progress
    ODB->>Cloud Foundry: create in progress
  end
  Cloud Foundry->>ODB: GET last operation
  ODB->>BOSH: GET task
  BOSH->>ODB: task done
  ODB->>Cloud Foundry: create succeeded
  User->>Cloud Foundry:cf service
  Cloud Foundry->>User: create succeeded
</div>
