<div class="mermaid">
sequenceDiagram
  User->> Cloud Controller: cf create-service
  Cloud Controller->> On Demand Broker: POST instance (create)
  On Demand Broker->>Service Adapter: generate-manifest
  Service Adapter->>On Demand Broker: manifest + secrets
  opt Secure Manifests enabled
    On Demand Broker->>BOSH CredHub: store secrets
    On Demand Broker->>On Demand Broker: update manifest with CredHub names
  end
  On Demand Broker->>BOSH: deploy
  BOSH->>On Demand Broker: accepted
  On Demand Broker->>Cloud Controller: accepted
  Cloud Controller->>User: create in progress
  loop while bosh deployment is in progress
    Cloud Controller->>On Demand Broker: GET last operation
    On Demand Broker->>BOSH: GET deploy task
    BOSH->>On Demand Broker: task in progress
    On Demand Broker->>Cloud Controller: create in progress
  end
  loop until there are no more post-deploy errands to run
    Cloud Controller->>On Demand Broker: GET last operation
    On Demand Broker->>BOSH: run next post-deploy errand
    BOSH->>On Demand Broker: accepted
    On Demand Broker->>Cloud Controller:create in progress
    loop while bosh task errand is in progress
      Cloud Controller->>On Demand Broker:GET last operation
      On Demand Broker->>BOSH:GET errand task
      BOSH->>On Demand Broker:task in progress
      On Demand Broker->>Cloud Controller:create in progress
    end
  end
  Cloud Controller->>On Demand Broker:GET last operation
  On Demand Broker->>BOSH:GET final errand task
  BOSH->>On Demand Broker:task done
  On Demand Broker->>Cloud Controller:create succeeded
  User->>Cloud Controller:cf service
  Cloud Controller->>User: create succeeded
</div>
