sequenceDiagram
  User->>CloudFoundry:delete-service
  CloudFoundry->>ODB:remove-instance
  ODB->>ServiceAdapter:pre-delete-deployment
  ServiceAdapter->>ODB:done
  ODB->>BOSH:bosh delete deployment
  BOSH->>ODB:accepted
  ODB->>CloudFoundry:accepted
  loop Until bosh task state is 'done'
    CloudFoundry->>ODB:last operation
    ODB->>BOSH:get task state
    BOSH->>ODB:queued/processing
    ODB->>CloudFoundry:in progress
  end
  CloudFoundry->>ODB:last operation
  ODB->>BOSH:get task state
  BOSH->>ODB:done
  ODB->>CloudFoundry:completed
