<div class="mermaid">
sequenceDiagram
  Operator->>Delete Errand:bosh run errand delete-all-service-instances-and-deregister-broker
  Delete Errand->>CF:POST disable-service-access
  CF->>Delete Errand:completed successfully
  Delete Errand->>CF:GET instances
  CF->>Delete Errand:instances
  loop for all instances
    Delete Errand->>CF:GET bindings
    CF->>Delete Errand:bindings
    loop for all bindings
    Delete Errand->>CF:cf unbind-service
      CF->>On Demand Broker: DELETE binding
      On Demand Broker->>Service Adapter:delete-binding
      Service Adapter->>On Demand Broker:exit code 0
      On Demand Broker->>CF:OK
      CF->>Delete Errand:OK
    end
    Delete Errand->>CF:GET service keys
    CF->>Delete Errand:service keys
    loop for all service keys
    Delete Errand->>CF:cf delete-service-key
      CF->>On Demand Broker: DELETE binding
      On Demand Broker->>Service Adapter:delete-binding
      Service Adapter->>On Demand Broker:exit code 0
      On Demand Broker->>CF:OK
      CF->>Delete Errand:OK
    end
    Delete Errand->>CF:cf delete-service
    CF->>On Demand Broker:DELETE instance
    On Demand Broker->>BOSH:delete deployment
    BOSH->>On Demand Broker:accepted
    On Demand Broker->>CF:accepted
    CF->>Delete Errand:accepted
    loop until DELETE completes
      Delete Errand->>CF:GET instance
      CF->>Delete Errand:delete instance in progress
      Note over CF,BOSH: CF asynchronously polls ODB, which in turn polls BOSH for last operation status
    end
    Delete Errand->>CF:GET instance
    CF->>Delete Errand:instance not found
  end
  Delete Errand->>CF:DELETE service-broker
  CF->>Delete Errand:completed successfully
  Delete Errand->>Operator:completed successfully
</div>
