<div class="mermaid">
sequenceDiagram
  User->>Cloud Controller:cf delete-service
  Cloud Controller->>On Demand Broker:DELETE instance
  On Demand Broker->>BOSH:delete deployment
  BOSH->>On Demand Broker:accepted
  On Demand Broker->>Cloud Controller:accepted
  Cloud Controller->>User: delete in progress
  loop until bosh task is complete
    Cloud Controller->>On Demand Broker: GET last operation
    On Demand Broker->>BOSH: GET task
    BOSH->>On Demand Broker: task in progress
    On Demand Broker->>Cloud Controller: delete in progress
  end
  Cloud Controller->>On Demand Broker: GET last operation
  On Demand Broker->>BOSH: GET task
  BOSH->>On Demand Broker: task done
  opt Secure Manifests enabled
    On Demand Broker->>BOSH Credhub: DELETE ODB-managed secrets
    BOSH Credhub->>On Demand Broker: delete secrets succeeded
  end
  On Demand Broker->>Cloud Controller: delete succeeded
  User->>Cloud Controller:cf service
  Cloud Controller->>User: not found
</div>
