<div class="mermaid">
sequenceDiagram
  Operator->>Delete Errand:bosh run errand delete-all-service-instances
  Delete Errand->>Cloud Controller:POST disable-service-access
  Cloud Controller->>Delete Errand:completed successfully
  Delete Errand->>Cloud Controller:GET instances
  Cloud Controller->>Delete Errand:instances
  loop for all instances
    Delete Errand->>Cloud Controller:GET bindings
    Cloud Controller->>Delete Errand:bindings
    loop for all bindings
    Delete Errand->>Cloud Controller:cf unbind-service
      Cloud Controller->>On Demand Broker: DELETE binding
      On Demand Broker->>Service Adapter:delete-binding
      Service Adapter->>On Demand Broker:exit code 0
      On Demand Broker->>Cloud Controller:OK
      Cloud Controller->>Delete Errand:OK
    end
    Delete Errand->>Cloud Controller:GET service keys
    Cloud Controller->>Delete Errand:service keys
    loop for all service keys
    Delete Errand->>Cloud Controller:cf delete-service-key
      Cloud Controller->>On Demand Broker: DELETE binding
      On Demand Broker->>Service Adapter:delete-binding
      Service Adapter->>On Demand Broker:exit code 0
      On Demand Broker->>Cloud Controller:OK
      Cloud Controller->>Delete Errand:OK
    end
    Delete Errand->>Cloud Controller:cf delete-service
    Cloud Controller->>On Demand Broker:DELETE instance
    On Demand Broker->>BOSH:delete deployment
    BOSH->>On Demand Broker:accepted
    On Demand Broker->>Cloud Controller:accepted
    Cloud Controller->>Delete Errand:accepted
    loop until DELETE completes
      Delete Errand->>Cloud Controller:GET instance
      Cloud Controller->>Delete Errand:delete instance in progress
      Note over Cloud Controller,BOSH: Cloud Controller asynchronously polls On Demand Broker, which in turn polls BOSH for last operation status
    end
    Delete Errand->>Cloud Controller:GET instance
    Cloud Controller->>Delete Errand:instance not found
  end
  Delete Errand->>Cloud Controller:DELETE service-broker
  Cloud Controller->>Delete Errand:completed successfully
  Delete Errand->>Operator:completed successfully
</div>
