<div class="mermaid">
sequenceDiagram
  Operator->>Delete Errand:bosh run errand delete-all-service-instances
  Delete Errand->>Cloud Foundry:GET instances
  Cloud Foundry->>Delete Errand:instances
  loop for all instances
    Delete Errand->>Cloud Foundry:GET bindings
    Cloud Foundry->>Delete Errand:bindings
    loop for all bindings
    Delete Errand->>Cloud Foundry:cf unbind-service
      Cloud Foundry->>On Demand Broker: DELETE binding
      On Demand Broker->>Service Adapter:delete-binding
      Service Adapter->>On Demand Broker:exit code 0
      On Demand Broker->>Cloud Foundry:OK
      Cloud Foundry->>Delete Errand:OK
    end
    Delete Errand->>Cloud Foundry:cf delete-service
    Cloud Foundry->>On Demand Broker:DELETE instance
    On Demand Broker->>BOSH:delete deployment
    BOSH->>On Demand Broker:accepted
    On Demand Broker->>Cloud Foundry:accepted
    Note over Cloud Foundry,BOSH:Cloud Foundry polls On Demand Broker for last operation until complete
    Cloud Foundry->>Delete Errand:completed
  end
  Delete Errand->>Operator:completed successfully
</div>
