<div class="mermaid">
sequenceDiagram
  Operator->>Delete Errand:bosh run errand delete-all-service-instances
  Delete Errand->>CF:GET instances
  CF->>Delete Errand:instances
  loop for all instances
    Delete Errand->>CF:GET bindings
    CF->>Delete Errand:bindings
    loop for all bindings
    Delete Errand->>CF:cf unbind-service
      CF->>ODB: DELETE binding
      ODB->>Service Adapter:delete-binding
      Service Adapter->>ODB:exit code 0
      ODB->>CF:OK
      CF->>Delete Errand:OK
    end
    Delete Errand->>CF:cf delete-service
    CF->>ODB:DELETE instance
    ODB->>BOSH:delete deployment
    BOSH->>ODB:accepted
    ODB->>CF:accepted
    Note over CF,BOSH:CF polls ODB for last operation until complete
    CF->>Delete Errand:completed
  end
  Delete Errand->>Operator:completed successfully
</div>
