<div class="mermaid">
sequenceDiagram
  User->>Cloud Foundry:cf delete-service
  Cloud Foundry->>ODB:DELETE instance
  ODB->>BOSH:run pre-delete errand
  BOSH->>ODB:accepted
  ODB->>Cloud Foundry:accepted
  Cloud Foundry->>User: delete in progress
  loop until errand bosh task is complete
    Cloud Foundry->>ODB:GET last operation
    ODB->>BOSH:GET errand task
    BOSH->>ODB:task in progress
    ODB->>Cloud Foundry:delete in progress
  end
  Cloud Foundry->>ODB:GET last operation
  ODB->>BOSH:GET errand task
  BOSH->>ODB:task done
  ODB->>BOSH:delete deployment
  BOSH->>ODB:accepted
  loop until delete deployment bosh task is complete
    Cloud Foundry->>ODB: GET last operation
    ODB->>BOSH: GET delete deployment task
    BOSH->>ODB: task in progress
    ODB->>Cloud Foundry: delete in progress
  end
  Cloud Foundry->>ODB: GET last operation
  ODB->>BOSH: GET delete deployment task
  BOSH->>ODB: task done
  ODB->>Cloud Foundry: delete succeeded
  User->>Cloud Foundry:cf service
  Cloud Foundry->>User: not found
</div>
