<div class="mermaid">
sequenceDiagram
  User->>Cloud Foundry:cf unbind-service
  Cloud Foundry->>ODB:DELETE binding
  ODB->>Service Adapter:delete-binding
  Service Adapter->>ODB:exit 0
  ODB->>Cloud Foundry:OK
  Cloud Foundry->>User:OK
</div>
