<div class="mermaid">
sequenceDiagram
  User->>Cloud Controller:cf unbind-service
  Cloud Controller->>On Demand Broker:DELETE binding
  On Demand Broker->>Service Adapter:delete-binding
  Service Adapter->>On Demand Broker:exit 0
  opt Secure Binding enabled
  On Demand Broker->>CredHub:Delete credentials
  CredHub->>On Demand Broker:OK
  end
  On Demand Broker->>Cloud Controller:OK
  Cloud Controller->>User:OK
</div>
