<div class="mermaid">
  sequenceDiagram
  User->> Cloud Controller: cf update-service -c '{"some":"config"}'
  Cloud Controller->> On Demand Broker: PATCH instance (update)
  On Demand Broker->>BOSH:GET manifest
  BOSH->>On Demand Broker:previous manifest
  opt Secure Manifests enabled
    On Demand Broker->>BOSH CredHub: GET previous secrets
    BOSH CredHub->>On Demand Broker: secrets
  end
  On Demand Broker->>Service Adapter: generate-manifest (without PATCH options)
  Service Adapter->>On Demand Broker: manifest
  On Demand Broker->>On Demand Broker: check for pending changes
  On Demand Broker->>Service Adapter: generate-manifest (with PATCH options)
  Service Adapter->>On Demand Broker: manifest + secrets
  opt Secure Manifests enabled
    On Demand Broker->>BOSH CredHub: store secrets
    On Demand Broker->>On Demand Broker: update manifest with CredHub names
  end
  On Demand Broker->>BOSH: deploy
  BOSH->>On Demand Broker: accepted
  On Demand Broker->>Cloud Controller: accepted
  Cloud Controller->>User: update in progress
  loop until bosh task is complete
    Cloud Controller->>On Demand Broker:GET last operation
    On Demand Broker->>BOSH:GET task
    BOSH->>On Demand Broker:task in progress
    On Demand Broker->>Cloud Controller:update in progress
  end
  Cloud Controller->>On Demand Broker:GET last operation
  On Demand Broker->>BOSH:GET task
  BOSH->>On Demand Broker:task done
  On Demand Broker->>Cloud Controller:update succeeded
  User->>Cloud Controller: cf service
  Cloud Controller->>User: update succeeded
</div>
