<div class="mermaid">
sequenceDiagram
  Operator->>Upgrade Errand:bosh run errand upgrade-all-service-instances
  Upgrade Errand->>CF:GET instances
  CF->>Upgrade Errand:instances
  loop for all instances
    Upgrade Errand->>ODB: PATCH instance (upgrade)
    ODB->>Service Adapter: generate-manifest
    Service Adapter->>ODB: manifest
    ODB->>BOSH: deploy
    BOSH->>ODB: accepted
    ODB->>Upgrade Errand: accepted
    Note over Upgrade Errand,BOSH: Upgrade Errand polls ODB for last operation until complete
  end
  Upgrade Errand->>Operator:completed successfully
</div>
