<div class="mermaid">
  sequenceDiagram
  User->> Cloud Foundry: cf update-service -c '{"apply-changes":true}'
  Cloud Foundry->> ODB: PATCH instance (update)
  ODB->>BOSH:GET manifest
  BOSH->>ODB:previous manifest
  ODB->>Service Adapter: generate-manifest
  Service Adapter->>ODB: manifest
  ODB->>BOSH: deploy
  BOSH->>ODB: accepted
  ODB->>Cloud Foundry: accepted
  Cloud Foundry->>User: update in progress
  loop until bosh task is complete
    Cloud Foundry->>ODB:GET last operation
    ODB->>BOSH:GET task
    BOSH->>ODB:task in progress
    ODB->>Cloud Foundry:update in progress
  end
  Cloud Foundry->>ODB:GET last operation
  ODB->>BOSH:GET task
  BOSH->>ODB:task done
  ODB->>Cloud Foundry:update succeeded
  User->>Cloud Foundry: cf service
  Cloud Foundry->>User: update succeeded
</div>
