<div class="mermaid">  
sequenceDiagram
User->> CloudFoundry: cf update service -c '{"apply-changes":true}'
  CloudFoundry->> ODB: update instance
 ODB->>ServiceAdapter: generate manifest with the old manifest & request parameters
  ServiceAdapter->>ODB: an updated deployment manifest
  ODB->>BOSH: bosh deploy with manifest
  BOSH->>ODB: deploying
  ODB->>CloudFoundry: accepted
  loop Until bosh task state is 'done'
    CloudFoundry->>ODB:last operation
    ODB->>BOSH:get task state
    BOSH->>ODB:queued/processing
    ODB->>CloudFoundry:in progress
  end
  CloudFoundry->>ODB:last operation
  ODB->>BOSH:get task state
  BOSH->>ODB:done
  ODB->>CloudFoundry:completed
</div>
