<div class="mermaid">
sequenceDiagram
  Operator->>Upgrade Errand:bosh run errand upgrade-all-service-instances
  Upgrade Errand->>On Demand Broker:GET instances
  On Demand Broker->>Cloud Controller:GET instances
  Cloud Controller->>Upgrade Errand:instances
  loop for all instances
    Upgrade Errand->>On Demand Broker: PATCH instance (upgrade)
    On Demand Broker->>Service Adapter: generate-manifest
    Service Adapter->>On Demand Broker: manifest
    On Demand Broker->>BOSH: deploy
    BOSH->>On Demand Broker: accepted
    On Demand Broker->>Upgrade Errand: accepted
    Note over Upgrade Errand,BOSH: Upgrade Errand polls On Demand Broker for last operation until complete
  end
  Upgrade Errand->>Operator:completed successfully
</div>
