---
template_variables:
  book_title: VMware Tanzu Documentation
  book_title_short: VMware Tanzu Docs
  title: <span class="title-deemph">VMware Tanzu</span> Documentation
  title_image: images/icon-p-green.jpg
  hero_text: "Detailed documentation to help you install, understand, and succeed with VMware's enterprise-grade software."

  tile_name: On-Demand Services SDK
  product_url: https://network.tanzu.vmware.com/products/pivotal-cf
  product_link: <div class="header-item"><a href="https://network.tanzu.vmware.com/products/pivotal-cf">Back to Product Page</a></div>

  support_link: <a href="http://tanzu.vmware.com/support" target="_blank">Support</a>
  support_call_to_action: <a href="http://tanzu.vmware.com/support" target="_blank">Need Support?</a>
  support_url: http://tanzu.vmware.com/support
  product_network: VMware Tanzu Network
  oss_releases: BOSH.io Releases

  path_to_partials: /svc-sdk/odb/partials

  api_version: 235
  gtm_account_id: GTM-MM86KCJ

  use_global_header: true
  global_header_product_href: https://network.tanzu.vmware.com/
  global_header_product_link_text: Downloads

  # Tanzu variables

  product_full: On-Demand Services SDK
  product_short: On-Demand Services SDK
  product_abbr: ODB

  app_runtime_full: VMware Tanzu Application Service for VMs
  app_runtime_abbr: TAS for VMs

  k8s_runtime_full: Tanzu Kubernetes Grid Integrated Edition
  k8s_runtime_abbr: TKGI

  windows_runtime_full: VMware Tanzu Application Service for VMs &#91;Windows&#93;
  windows_runtime_abbr: TAS for VMs &#91;Windows&#93;

  segment_runtime_full: Isolation Segment

  ops_manager: Tanzu Operations Manager
  
  # Associated Tanzu Application Service for VMs version
  current_tas_version: "4-0"
  v_major_tas_version: "v4.0"
  dot_major_tas_version: "4.0"
  # Used in docs-partials, for TAS version
  current_major_version: "4-0"

  # Pivotal variables

  platform_name: Pivotal Platform
  platform_old: Pivotal Cloud Foundry
  platform_code: PCF
  product_name_lc: pcf

  product_full_pivotal: On-Demand Services SDK
  product_short_pivotal: On-Demand Services SDK
  product_abbr_pivotal: ODB

  product_old: On-Demand Services SDK

  service_name: service
  service_name_article: the service
  service_name_article_full: the on-demand service

  app_runtime_full_pivotal: Pivotal Application Service
  app_runtime_abbr_pivotal: PAS

  k8s_runtime_full_pivotal: Pivotal Container Service

  windows_runtime_full_pivotal: Pivotal Application Service for Windows
  windows_runtime_abbr_pivotal: PASW

  segment_runtime_full_pivotal: Pivotal Isolation Segment

  ops_manager_full: VMware Tanzu Operations Manager

  odb_bosh_lite_version: v9000.131.0
  odb_example_redis_service_adapter_version: master
  odb_pcfdev_version_pivnet: 1811
  odb_pcfdev_version: pcfdev-v0.19.1-rc.46
  odb_warden_stemcell_version: 3262.2
